# runs daily at 6:00 UTC and tweets the next part of the poem

name: Daily CI Post

on:
  # manually triggered
  workflow_dispatch:
  schedule:
    # daily at 6:00 UTC
    - cron: "0 6 * * *"

jobs:
  daily_post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: current-position

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily_post.py
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          python onegin_paste_bot.py

      - name: Commit and push
        run: |
          git config --global user.email github-actions
          git config --global user.name github-actions@github.com
          git add .
          git commit -m "Daily CI Post: update current position"
          git push